version: "3.3"
services:
  api:
    container_name: api_vlad
    build: ./myapp
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bot_vk_vlad
      - DB_HOST=db
      - PORT=5001
      - NODE_ENV=development
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - 5001:5001
    command: npm run start
    restart: always
volumes:
  pg_data:
networks:
  ms_network:
    external: true
